version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: discord-clone-postgres
    environment:
      POSTGRES_DB: discord_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - discord-clone-network

volumes:
  postgres_data:

networks:
  discord-clone-network:
    driver: bridge